const data = [
  {
    id: 5714270020,
    category: "ИСиТ-19",
    name: "Романов Роман Артёмович",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 1514270021,
    category: "ИСиТ-19",
    name: "Островская Амина Ивановна",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 7514270021,
    category: "БИ-19",
    name: "Малышев Максим Владиславович",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 8314270021,
    category: "БИ-19",
    name: "Зотова Ирина Арсентьевна",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 3514270021,
    category: "БИ-19",
    name: "Леонова Варвара Михайловна",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 8214270020,
    category: "ИСиТ-19",
    name: "Коровин Денис Миронович",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 7414270021,
    category: "ИСиТ-19",
    name: "Соколов Кирилл Николаевич",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 5714270021,
    category: "БИ-19",
    name: "Савин Матвей Васильевич",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 9534270021,
    category: "ИСиТ-19",
    name: "Тарасова Екатерина Андреевна",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
  {
    id: 1581270021,
    category: "ИСиТ-19",
    name: "Горюнова Анастасия Львовна",
    documentsSeries: 939,
    competitiveScore: 0,
    privileges: false,
    primary: true,
    formEducation: "Очная",
  },
];

export default data;
